### ISSUE TITLE
There are no commands defined in the "candy" namespace.

### ISSUE THREAD

**Issue by abhishekgautam2014** [getcandy/candy-api#10]
candy install command not working .
thanks

**Comment by dhonions** [comment]
They are there since I used it:  php artisan candy:install

**Comment by alecritson** [comment]
If you're using Laravel >= 5.6 then it should autodiscover the service provider, otherwise you will need to add `GetCandy\Api\Providers\ApiServiceProvider::class` to your `app.php` config, this will register the commands for you.

**Comment by devkomtorg** [comment]
php artisan candy:install


  There are no commands defined in the "candy" namespace.



candy install command not working
