### ISSUE TITLE
When im install it alert artisan not found, any idea?

### ISSUE THREAD

**Issue by pson90** [getcandy/candy-api#100]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by alecritson** [comment]
Are you running `php artisan ... ` from inside the project root?

**Comment by pson90** [comment]
Yes, i am newber about laravel, do you have document introduction to setup your project. Your project really awesome.

**Comment by alecritson** [comment]
Hey @pson90 

We've recently wrote an article on how to get set up from scratch 

https://medium.com/getcandy/installing-getcandy-from-scratch-39302a988ffb
