### ISSUE TITLE
When install project, i get this error, about passport

### ISSUE THREAD

**Issue by pson90** [getcandy/candy-api#101]
Problem 1
    - The requested package laravel/passport (locked at v5.0.3, required as ^7.0) is satisfiable by laravel/passport[v5.0.3] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Conclusion: don't install laravel/passport v7.0.5
    - Conclusion: don't install laravel/passport v7.0.4
    - Conclusion: don't install laravel/passport v7.0.3
    - Conclusion: don't install laravel/passport v7.0.2
    - getcandy/candy-hub v0.1.4 requires laravel/passport ^7.0 -> satisfiable by laravel/passport[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5].
    - Conclusion: don't install laravel/passport v7.0.1
    - Installation request for getcandy/candy-hub ^0.1.4 -> satisfiable by getcandy/candy-hub[v0.1.4].
    - Conclusion: remove league/oauth2-server 6.1.1
    - Conclusion: don't install league/oauth2-server 6.1.1
    - laravel/passport v7.0.0 requires league/oauth2-server ^7.0 -> satisfiable by league/oauth2-server[7.0.0, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.3.1, 7.3.2].
    - Can only install one of: league/oauth2-server[7.0.0, 6.1.1].
    - Can only install one of: league/oauth2-server[7.1.0, 6.1.1].
    - Can only install one of: league/oauth2-server[7.1.1, 6.1.1].
    - Can only install one of: league/oauth2-server[7.2.0, 6.1.1].
    - Can only install one of: league/oauth2-server[7.3.0, 6.1.1].
    - Can only install one of: league/oauth2-server[7.3.1, 6.1.1].
    - Can only install one of: league/oauth2-server[7.3.2, 6.1.1].
    - Installation request for league/oauth2-server (locked at 6.1.1) -> satisfiable by league/oauth2-server[6.1.1].

**Comment by alecritson** [comment]
Hey @pson90 

This was due to `0.1.*` not supporting Laravel 5.7, you can use `0.2.0` which should work.
