### ISSUE TITLE
Error Undefind Value

### ISSUE THREAD

**Issue by Hkarimi561** [getcandy/candy-api#11]
Server error: `POST http://.../api/oauth/token` resulted in a `500 Internal Server Error` response: <!DOCTYPE html><!-- ErrorException: Undefined variable: language (View: /home/.../public_html/resources/views/_i (truncated...) (View: /home/.../public_html/resources/views/_layouts/base.blade.php) (View: /home/.../public_html/resources/views/_layouts/base.blade.php)

**Comment by dhonions** [comment]
Did you put the oauth details in your .env file?

CANDY_API_URL=http://candy-store.local/api/v1
CANDY_API_VERIFY=true
CANDY_API_ID=1
CANDY_API_SECRET=SwrzLLrsBtFv3qgssGKXXXY1Z13aAw3oTrAcN

**Comment by Hkarimi561** [comment]
i put the oath token correctly in .env but it has error

**Comment by alecritson** [comment]
This should be resolved in the 52167b59139d423c67a7260a7b5fbf175edfc361 commit, which will go into the next release
