### ISSUE TITLE
When edit product variant option it duplicates variants

### ISSUE THREAD

**Issue by ahmad753** [getcandy/candy-api#119]
When trying to edit a variant option it duplicate the variants, The issue is in productVariantService.php create function, there is a condition to check if the product variants count == 1 this makes the issue

## Expected Behavior
the condition should be $product->variants->count() >= 1

## Possible Solution
$product->variants->count() == 1

## Steps to Reproduce
1. Add a product
2. Add product variants then save 
3. Try to edit variant options

**Comment by alecritson** [comment]
There have been quite a few updates since this was reported. Closing to tidy things up, if this is still an issue feel free to re open.
