### ISSUE TITLE
great job!

### ISSUE THREAD

**Issue by wjllance** [getcandy/candy-api#12]
As a beginner, I wonder if i should make "composer require ..." command on a new directory or a laravel project?
Thx!
And it would be very nice if you could provide more detail document or some guide for a new beginner.

**Comment by alecritson** [comment]
Thanks for the feedback, you can find a basic wiki over https://github.com/getcandy/candy-store/wiki
we are working on the documentation as quick as we can so it's clearer how to get set up.
