### ISSUE TITLE
#1215 - Cannot add foreign key constraint

### ISSUE THREAD

**Issue by floreich** [getcandy/candy-api#120]
When trying to install the hub on top of the api using "php artisan candy:install" the migrations throw the following error.

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `user_details` add constraint `user_details_user_id_foreign` foreign key (`user_id`) references `users` (`id`))

**Comment by alecritson** [comment]
Do you have your base users migrations in the app?

**Comment by floreich** [comment]
I followed the documentation to install it. I followed all the steps, but still this error occurs when trying to install the app.

**Comment by alecritson** [comment]
What version of Laravel are you using? If you're trying to install on 5.8, we haven't done the upgrade yet.

**Comment by floreich** [comment]
it's fixed. Thanks for help. Appreciated
