### ISSUE TITLE
install error :  Data too long for column 'name' in table `countries`

### ISSUE THREAD

**Issue by ChDUP** [getcandy/candy-api#121]
Hi

During the install, php artisan candy:install, I got this this error
` String data, right truncated: 1406 Data too long for column 'name' at row 1 (SQL: insert into countries`

I'm using dockere environment , with php 7.3.0 and mysql 8.0.15
T've tried several fixes, but still has this problem.

Thanks for your help

**Comment by alecritson** [comment]
Hey @ChDUP 

This should be fixed in the latest release, so just run `composer update getcandy/candy-api` and try again, if it doesn't solve your issue, just let us know.

**Comment by ChDUP** [comment]
works great with this release, Thanks.
Install is completed now, I have another problem but I will open another issue for this.
