### ISSUE TITLE
Bug for new Product Families

### ISSUE THREAD

**Issue by youyi1314** [getcandy/candy-api#125]
Can't edit for new added Product Families. 

![image](https://user-images.githubusercontent.com/8391468/54609671-6877bd80-4a8e-11e9-99b1-0356dee531c3.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/8391468/54609815-9f4dd380-4a8e-11e9-8936-b6785b6c4e30.png)

## Current Behavior
Name and Description form not load also list in [**Attribute Group**] also not load as photo above show.

## Possible Solution
I think it should be a bug that did not load or create the required field after create new Product Families

## Steps to Reproduce
1. Go to [Catalogue Manager] at top menu
2. Click [Product Families] at Left Menu
3. Click [+ Create Product Family]
4. Insert any name in Input Form and Click [Save]
5. Click the name you create at step 5, and bug

## Context (Environment)
"getcandy/candy-api": "0.2.*",
"getcandy/candy-hub": "0.2.*",
"laravel/framework": "5.7.*",

## Detailed Description
Unknow
## Possible Implementation
Unknow

**Comment by alecritson** [comment]
Hey @youyi1314 This should be resolved in `0.2.19` of the Hub, reopen if it doesn't solve the issue. :)
