### ISSUE TITLE
Cannot assign category to products

### ISSUE THREAD

**Issue by steveadamsfixedit** [getcandy/candy-api#130]
I've installed the api and the hub version 0.2 onto a fresh install of laravel 5.7 and have a functional hub backend. I can add products collections, and categories...however, there  is a snag furthering the store:

1) the category manager functionally DOES allow for the creation of categories and sub categories...but when you try to add a new category or child and click "save" nothing happens. I'd expect some "new category saved" message and a reload of the page. If I refresh the page, the new category shows. It works as expected on the collections.

2) when trying to edit the catalog and assign a category to a product, I start typing and the loading wheel just spins and does not locate any category to assign to the product. It works as expected with collections.

please advise

**Comment by steveadamsfixedit** [comment]
Received note from another off thread post response, but thought I'd address it here and close the other issue--

recommended upgrate to the api and hub...
getcandy/candy-api                    0.2.37            
getcandy/candy-hub                    0.2.21           

Issues still unresolved

**Comment by alecritson** [comment]
This should be sorted in the latest hub and API. If not please reopen.
