### ISSUE TITLE
How do implement user login?

### ISSUE THREAD

**Issue by francishero** [getcandy/candy-api#133]
Having same issue as https://github.com/getcandy/candy-api/issues/73

**Comment by alecritson** [comment]
GetCandy uses [Laravel Passport](https://laravel.com/docs/5.7/passport) so you just need to really follow the steps on their documentation, use the [password grant](https://laravel.com/docs/5.7/passport#password-grant-tokens) and pass the token as an authorization header like `Authorization Bearer <token>` and you should be authenticated.

If want to use the API as a guest, you still need a token, for that you can just use a [Client token](https://laravel.com/docs/5.7/passport#client-credentials-grant-tokens).

**Comment by heromiyo** [comment]
OK thanks

**Comment by francishero** [comment]
Ok thanks
