### ISSUE TITLE
api/eloquent scoping

### ISSUE THREAD

**Issue by pjonckiere** [getcandy/candy-api#136]
## Expected Behavior
When creating a product in code, I try to immediately fetch it, but it is not found. 

As another example, when creating a category in code, it won't fill in the expected values for the _lft and _rgt properties 

## Current Behavior

Fetching the newly created product yields no results.

## Steps to Reproduce

~~~
$product = app('api')->products()->create($productFields);
$test = app('api')->products()->getByHashedId($product->encodedId());
~~~

This might be related to eloquent scoping? I noticed there is customer_group scoping and channel scoping, however, I'm uncertain how to "set" it. 

Could you provide any insight on this? Or point me to some documentation that could be helpful?

**Comment by alecritson** [comment]
You're doing this from within your own laravel app I take it?

There is a middleware which sets the channel, but you can do it a few ways.

You can add the `api.channels` middleware to your route and then you can pass `X-CANDY-CHANNEL` header (or omit it as it should use the default in the database)

Or you can DI the channel factory and set it yourself manually

```
// This will give you a singleton instance
use GetCandy\Api\Core\Channels\Interfaces\ChannelFactoryInterface;

public function __construct(ChannelFactoryInterface $channels)
{
 $channels->set('webstore');
}
```

Does this help?

**Comment by pjonckiere** [comment]
> You're doing this from within your own laravel app I take it?

That is correct.

I did try the middleware approach, but with no luck.

I just tried injecting the channel factory and setting the channel. I also tried setting the groups like the middleware does. Still no luck.

~~~
        $groups = app('api')->customerGroups()->all();
        GetCandy::setGroups($groups);
~~~

I do think setting we are thinking in the right direction, since I do get the expected result when I comment out the scopes in Product.php (line 80-81):

~~~
//        static::addGlobalScope(new CustomerGroupScope);
//        static::addGlobalScope(new ChannelScope);
~~~

**Comment by alecritson** [comment]
In the channel and customer group link tables is there a value for `published_at` and `visible` in the respective columns? Also maybe try commenting out each one at a time to narrow down the culprit

**Comment by pjonckiere** [comment]
I changed the published_at property in my creation fields from null to Carbon::now(), and it seems to work as expected now! This still includes the ad-hoc injection fix from above, which I'll try to replace with the middleware again.

I still have a similar issue with categories, but I think I'll be able to figure it out with the info provided here.

Thanks for the support!
