### ISSUE TITLE
Laravel 5.8 - Call to undefined method "Dispatcher::fire()"

### ISSUE THREAD

**Issue by flavius-constantin** [getcandy/candy-api#162]
## Steps to Reproduce
1. [Install GetCandy (API & Hub)](https://getcandy.io/docs/master/guides/introduction/01-installation) 
2. Go to getcandy.test/hub
3. Log in with your credentials
4. -> Error (Attachment)

## Possible Solution
<img width="584" alt="Bildschirmfoto 2019-07-28 um 19 30 56" src="https://user-images.githubusercontent.com/23703860/62010748-fff0c980-b16e-11e9-8703-caf1e97e711f.png">

Read more - [Laravel Upgrade Guide](https://laravel.com/docs/5.8/upgrade)

## Attachment/Description
<img width="356" alt="Bildschirmfoto 2019-07-28 um 19 36 09" src="https://user-images.githubusercontent.com/23703860/62010749-fff0c980-b16e-11e9-9aca-0139f6150a7e.png">

**Comment by alecritson** [comment]
Thanks for this, should be fixed in [0.2.43](https://github.com/getcandy/candy-hub/releases/tag/0.2.43) of the hub.
