### ISSUE TITLE
Failure on Installation

### ISSUE THREAD

**Issue by iDustbin** [getcandy/candy-api#163]

**Comment by alecritson** [comment]
Based on your edit, has this been sorted?

**Comment by iDustbin** [comment]
you have to edit app/User.php
`<?php
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GetCandy\Api\Core\Traits\HasCandy;

class User extends Authenticatable

{
    use HasCandy;

   /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}`

**Comment by alecritson** [comment]
Yeah, you just need to add the trait
