### ISSUE TITLE
elastisearch not working ? 

### ISSUE THREAD

**Issue by iDustbin** [getcandy/candy-api#164]
curl localhost:9200/candy
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [candy]","resource.type":"index_or_alias","resource.id":"candy","index_uuid":"_na_","index":"candy"}],"type":"index_not_found_exception","reason":"no such index [candy]","resource.type":"index_or_alias","resource.id":"candy","index_uuid":"_na_","index":"candy"},"status":404}

curl localhost:9200/candy_products_en
{"candy_products_en_1565179355.6303":{"aliases":{"candy_products_en":{}},"mappings":{"properties":{"breadcrumbs":{"type":"text","fields":{"en":{"type":"text","analyzer":"english"}},"analyzer":"standard"},"channels":{"type":"nested","properties":{"handle":{"type":"keyword"},"id":{"type":"keyword"},"name":{"type":"text"}}},"created_at":{"type":"date"},"customer_groups":{"type":"nested","properties":{"handle":{"type":"keyword"},"id":{"type":"keyword"},"name":{"type":"text"}}},"departments":{"type":"nested","properties":{"id":{"type":"keyword"},"position":{"type":"integer"}}},"description":{"type":"text","analyzer":"standard"},"id":{"type":"text"},"max_price":{"type":"scaled_float","scaling_factor":100.0},"meta_description":{"type":"text","fields":{"sortable":{"type":"keyword"}},"analyzer":"standard"},"meta_keywords":{"type":"text","fields":{"sortable":{"type":"keyword"}},"analyzer":"standard"},"min_price":{"type":"scaled_float","scaling_factor":100.0},"name":{"type":"text","fields":{"en":{"type":"text","analyzer":"english"},"sortable":{"type":"keyword"},"suggest":{"type":"completion","analyzer":"simple","preserve_separators":true,"preserve_position_increments":true,"max_input_length":50},"trigram":{"type":"text","analyzer":"trigram"}},"analyzer":"standard"},"page_title":{"type":"text","fields":{"sortable":{"type":"keyword"}},"analyzer":"standard"},"popularity":{"type":"integer"},"pricing":{"type":"nested","properties":{"id":{"type":"keyword"},"max":{"type":"scaled_float","scaling_factor":100.0},"min":{"type":"scaled_float","scaling_factor":100.0},"name":{"type":"text"}}},"short_description":{"type":"text","fields":{"sortable":{"type":"keyword"}},"analyzer":"standard"},"sku":{"type":"text","fields":{"lowercase":{"type":"text","analyzer":"standard_lowercase"},"sortable":{"type":"keyword"},"suggest":{"type":"completion","analyzer":"simple","preserve_separators":true,"preserve_position_increments":true,"max_input_length":50}},"analyzer":"standard"}}},"settings":{"index":{"number_of_shards":"1","provided_name":"candy_products_en_1565179355.6303","creation_date":"1565179355641","analysis":{"filter":{"shingle":{"max_shingle_size":"3","min_shingle_size":"2","type":"shingle"}},"analyzer":{"candy":{"filter":["lowercase","stop","porter_stem"],"tokenizer":"standard"},"trigram":{"filter":["shingle"],"type":"custom","tokenizer":"standard"},"standard_lowercase":{"filter":["lowercase"],"type":"custom","tokenizer":"standard"}}},"number_of_replicas":"1","uuid":"yJK-X9-aQ2WaE1Y7KMv0tQ","version":{"created":"7030099"}}}}}

anything missing ? in config/getcandy.php i added under elasticsearch host:127.0.0.1 and port.9200

**Comment by alecritson** [comment]
I think you need to index your products with `php artisan candy:search:index`

**Comment by iDustbin** [comment]
i made this already... 
php artisan candy:search:index

Indexing GetCandy\Api\Core\Products\Models\Product
...:batch:0Indexing GetCandy\Api\Core\Categories\Models\Category
...:batch:0Done!

curl http://fqdn:8000/api/v1/categories 
i added 3xcategories and elk response is only 1x category...

**Comment by iDustbin** [comment]
curl 'localhost:9200/_cat/indices?v'
health status index                               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   candy_categories_en_1565181994.7241 _zPNGMMrTBmFLHGwMLf9Ig   1   1          4            4     11.7kb         11.7kb
yellow open   candy_products_en_1565181994.3647   x9ma9qWXRCGmeVQdzST95w   1   1          6            6     15.1kb         15.1kb

**Comment by iDustbin** [comment]
GET /api/v1/product-families HTTP/1.1

HTTP/1.1 500 Internal Server Error

vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php

    public function route($name, $parameters = [], $absolute = true)
    {
        if (! is_null($route = $this->routes->getByName($name))) {
            return $this->toRoute($route, $parameters, $absolute);
        }
 
        throw new InvalidArgumentException("Route [{$name}] not defined.");
    }

**Comment by alecritson** [comment]
You might need to set `SEARCH_INDEX` in your `.env` file ?

**Comment by iDustbin** [comment]
nope... could you please share the required settings ?

**Comment by iDustbin** [comment]
https://github.com/getcandy/candy-hub/blob/master/.env.example 
thx

**Comment by alecritson** [comment]
Do you mean you haven't set it? The required setting is `SEARCH_INDEX={YOUR_INDEX}`

**Comment by iDustbin** [comment]
sry im to stupid... 
could you help me to define my prefix and search index ? 

curl 'localhost:9200/_search/'
{"took":12,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":3,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"candy_categories_en_1565184165.7275","_type":"categories","_id":"v8l4pl01","_score":1.0,"_source":{"id":"v8l4pl01","departments":[],"customer_groups":[{"id":"v8l4pl01","handle":"retail","name":"Retail"},{"id":"p09prlrn","handle":"guest","name":"Guest"}],"channels":[{"id":"y3g6v91o","handle":"shop","name":"shop"}],"breadcrumbs":"","name":"Feld- & Wiesenbearbeitung","description":"lorem ipsum"}},{"_index":"candy_products_en_1565184165.1696","_type":"products","_id":"xojxzgy5","_score":1.0,"_source":{"id":"xojxzgy5","departments":[{"id":"v8l4pl01","name":"Feld- & Wiesenbearbeitung","position":1}],"customer_groups":[{"id":"v8l4pl01","handle":"retail","name":"Retail"},{"id":"p09prlrn","handle":"guest","name":"Guest"}],"channels":[{"id":"y3g6v91o","handle":"shop","name":"shop"}],"breadcrumbs":"Feld- & Wiesenbearbeitung","name":"Schlegelmulcher","pricing":[{"id":"v8l4pl01","name":"Retail","min":"1299.00000","max":"1299.00000"},{"id":"p09prlrn","name":"Guest","min":"1299.00000","max":"1299.00000"}],"min_price":"1299.00000","max_price":"1299.00000","sku":["EFGHC-105"]}},{"_index":"candy_products_en_1565184165.1696","_type":"products","_id":"m4j5lnp7","_score":1.0,"_source":{"id":"m4j5lnp7","departments":[],"customer_groups":[{"id":"v8l4pl01","handle":"retail","name":"Retail"},{"id":"p09prlrn","handle":"guest","name":"Guest"}],"channels":[{"id":"y3g6v91o","handle":"shop","name":"shop"}],"breadcrumbs":"","name":"test","pricing":[{"id":"v8l4pl01","name":"Retail","min":"1288.00000","max":"1288.00000"},{"id":"p09prlrn","name":"Guest","min":"1288.00000","max":"1288.00000"}],"min_price":"1288.00000","max_price":"1288.00000","sku":["test"]}}]}}

curl 'localhost:9200/candy_products_en'

**Comment by iDustbin** [comment]
could you share youre default values ?
