### ISSUE TITLE
Cannot install app in sub directory 

### ISSUE THREAD

**Issue by sadiss** [getcandy/candy-api#165]
## Expected Behavior
Application should make calls through sub bolder like this
https://www.example.com/subfolder/api/vi/...
## Current Behavior

Right now my application is in 
https://www.example.com/subfolder/
but application is requesting data for dashboard from this url
https://www.example.com/api/vi/...

## Possible Solution
read data through .env file or provide a configuration file via --publish

**Comment by alecritson** [comment]
You would need to add your sub folder name to the start of `/api/v1` when you register your routes. Or look at how you should be adding your laravel app to a sub folder using `.htaccess` or `nginx`. I don't think this is a GetCandy issue as such.
