### ISSUE TITLE
Laravel Version & Payments

### ISSUE THREAD

**Issue by Christophvh** [getcandy/candy-api#170]
Hi,

Thanks for making this package and making it open source!

We are considering this for a future project, but got a couple of concerns.

The Laravel dependency in the current composer.json still requires Laravel 5.7. Will this be updated to Laravel 6 in the nearby future or is it currently version locked? 

In the docs, it is clearly stated that we can add our own payment-provider but it seems limited since we still have to adhere to the candy interface. We want to use Laravel-cashier or Laravel cashier with mollie. I assume using all features of Laravel-cashier will not be possible and we have to add Stripe/Mollie separately as a payment provider?.

**Comment by alecritson** [comment]
Hey @Christophvh 

Thanks for the interest!

We are looking to get it to the latest version of Laravel as soon as possible, we're going to be pushing for a beta release in the near future and I'd assume that's when we'll update the dependancy.

As for payments, were there any particular features in Cashier you noticed you'd need?

**Comment by Christophvh** [comment]
Thanks for the response. This is nice to hear! 

Not to rush anybody or expect anything, but do you have time-frame on this beta-release. Is it weeks/months etc.

Cashier offers some invoicing support, refunding, also Cashier is fully ready for the new SCA regulation.  https://laravel.com/docs/6.x/billing#strong-customer-authentication . Which is not that easy to implement yourself. But if it is easy in this package to add stripe/mollie as payment gateway we can use their external payment-pages which solves that issue.

**Comment by Khalilbz** [comment]
When we will have the beta version ??

**Comment by alecritson** [comment]
We are now on version `0.11` which is out of beta. We also have plans for a payments module which you can follow here #337
