### ISSUE TITLE
Laravel 6 couldn't install candy-api or candy-hub

### ISSUE THREAD

**Issue by emrulmax2** [getcandy/candy-api#190]
Get candy couldn't install after using composer command

## Current Behavior

Candy Hub shows this error

  Problem 1
    - getcandy/candy-hub 0.3.x-dev requires tightenco/ziggy ^0.6.9 -> satisfiable by tightenco/ziggy[v0.6.9] but these conflict with your requirements or minimum-stability.
    - getcandy/candy-hub 0.3.16 requires tightenco/ziggy ^0.6.9 -> satisfiable by tightenco/ziggy[v0.6.9] but these conflict with your requirements or minimum-stability.
    - Installation request for getcandy/candy-hub ^0.3.16 -> satisfiable by getcandy/candy-hub[0.3.16, 0.3.x-dev].

Candy Api shows this error
    - Installation request for laravel/tinker (locked at v2.1.0, required as ^2.0) -> satisfiable by laravel/tinker[v2.1.0].
    - getcandy/candy-api 0.3.35 requires laravel/tinker ^1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - getcandy/candy-api 0.3.x-dev requires laravel/tinker ^1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - Conclusion: don't install laravel/tinker 1.x-dev
    - Installation request for getcandy/candy-api ^0.3.35 -> satisfiable by getcandy/candy-api[0.3.35, 0.3.x-dev].
## Possible Solution

please need a update for laravel 6.2 +

**Comment by plakhin** [comment]
Any updates on this issue? Is candi-api and candy-hub going to be updated to support Latavel 7 or at least Laravel 6.x LTS?

**Comment by alecritson** [comment]
We're working on the beta launch which will support these versions. We've just been playing catch up with a few things but we're making good progress.

**Comment by plakhin** [comment]
@alecritson any way to try this beta?

how complicated will be the process of upgrading from current version?

**Comment by plakhin** [comment]
@alecritson I'm starting new project and rather start with beta and help fix some issues via PRs than start with very outdated Laravel version and get complicated update/upgrade process.

Can you help me with this please?

**Comment by od3n** [comment]
> We're working on the beta launch which will support these versions. We've just been playing catch up with a few things but we're making good progress.

how do i require `release/0.9.0_beta` branch?

i tried `composer require getcandy/candy-api:dev-release/0.9.0_beta`

but getting these errors

```
  Problem 1
    - Installation request for getcandy/candy-api dev-release/0.9.0_beta -> satisfiable by getcandy/candy-api[dev-release/0.9.0_beta].
    - getcandy/candy-api dev-release/0.9.0_beta requires neondigital/laravel-drafting dev-master -> no matching package found.
```

**Comment by alecritson** [comment]
We’ve now some documentation on how to use the beta if you’re still thinking of using it, here’s the link https://guides.getcandy.io/api/installation.html#requirements
