### ISSUE TITLE
Where is API documentation?

### ISSUE THREAD

**Issue by emrulmax2** [getcandy/candy-api#191]
I couldn't find any api documentation for this? and couldn't work on Postman each api call get a login method not defined, I only want my products list via api how can I get that? because whenever I tried my development server http://127.0.0.1:8000/api/v1/products , only login method not define error given.

**Comment by emrulmax2** [comment]
InvalidArgumentException: Route [login] not defined. in file D:\wamp\www\attamoida_lara5\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php on line 388
Stack trace:

**Comment by alecritson** [comment]
We now have guides and api docs here:


https://guides.getcandy.io
Https://api-docs.getcandy.io

Any other issues please reopen
