### ISSUE TITLE
laravel 5.8 installation error

### ISSUE THREAD

**Issue by mckenziearts** [getcandy/candy-api#193]
After installing everything, i ran the command `artisan candy:install` and a i got this error

<img width="964" alt="Untitled" src="https://user-images.githubusercontent.com/14105989/76606443-8e556800-6512-11ea-992f-c714675c71a3.png">

**Comment by alecritson** [comment]
Hey @mckenziearts we're currently working on a beta release which should support these versions, there will be a few core changes so the docs will be available on release too.

**Comment by milosdakic** [comment]
@alecritson how are you guys going with the beta release? I've been trying to get this working on my current site. At the moment had to clone the two packages and make a few changes.

Would you guys consider PR's if I can get the code working? Or are you going to be bringing this up on your own?

PS. Awesome work, I really like the way this is looking.

**Comment by alecritson** [comment]
We’ve released the beta with guides here https://guides.getcandy.io/api/installation this requires l7 so I’d consider 5.8 unsupported going forward :)
