### ISSUE TITLE
SQLSTATE[HY000]: General error: 1005 Can't create table `db_grocery`.`versions` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alte r table `versions` add constraint `versions_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete SET NULL)

### ISSUE THREAD

**Issue by droidrobin** [getcandy/candy-api#197]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by droidrobin** [comment]
Resolve this issue?

**Comment by bekee** [comment]
Issue is coming from neondigital/laravel-versioning, when can this be resolved for Laravel 7

**Comment by alecritson** [comment]
The PR for the fix has been merged, try running composer update on the Laravel-versioning package and it should bring it down
