### ISSUE TITLE
New User Role Issue

### ISSUE THREAD

**Issue by bekee** [getcandy/candy-api#198]
What's your name?:
 > Dtoxxxxx

 What's your email?:
 > xxxxxxx@googlemail.com

 Choose a password (hidden):
 >

 Confirm it (hidden):
 >

Just creating your account now

   BadMethodCallException 

  Call to undefined method App\User::assignRole()

  at C:\xampp\htdocs\laravel\personal\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:50
    46|      * @throws \BadMethodCallException
    47|      */
    48|     protected static function throwBadMethodCallException($method)
    49|     {
  > 50|         throw new BadMethodCallException(sprintf(
    51|             'Call to undefined method %s::%s()', static::class, $method
    52|         ));
    53|     }
    54| }

  • Bad Method Call: Did you mean App\User::asJson() ?

  1   C:\xampp\htdocs\laravel\personal\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:36
      Illuminate\Database\Eloquent\Model::throwBadMethodCallException("assignRole")

  2   C:\xampp\htdocs\laravel\personal\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1728
      Illuminate\Database\Eloquent\Model::forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), "assignRole")

Run into the above issue after entering email and password with the command  php artisan candy:install

**Comment by alecritson** [comment]
Have you added the HasCandy trait to your user model?

**Comment by bekee** [comment]
Thanks. it's working now.

When will support for Elasticsearch  ^ 7.0 be added?

**Comment by alecritson** [comment]
Glad it’s working! I’ll close this issue, as for elastic 7, we’ll be looking into it as soon as possible :)
