### ISSUE TITLE
Authentication with the Admin Hub using Laravel Sanctum

### ISSUE THREAD

**Issue by jbaron-mx** [getcandy/candy-api#207]
I'm struggling to get the authentication working with the Admin Hub.
I have the API working with Sanctum, and I've tested it by calling some endpoints. However, I'm not sure how to configure the `PROXY_LOGIN_ENDPOINT` in the Hub side to get it working with the API and Sanctum.

I don't mean to rush you guys, but hopefully, you can write up the guide here https://guides.getcandy.io/hub/authentication.html#laravel-sanctum

**Comment by alecritson** [comment]
Hey @jbaron-mx 

Thanks for bringing this up. As this is more related to could you possibly post this on the hub repo? https://github.com/getcandy/hub :)
