### ISSUE TITLE
Use of deprecated unparenthesized nested ternary operators in the search controller (PHP 7.4)

### ISSUE THREAD

**Issue by Repox** [getcandy/candy-api#219]
## Expected Behavior

No deprecations notice

## Current Behavior
Error Exception is thrown with the following error message:

    Unparenthesized `a ?: b ? c : d` is deprecated. Use either `(a ?: b) ? c : d` or `a ?: (b ? c : d)`

## Possible Solution

Parenthesize the nested operators.

## Steps to Reproduce
1. Install PHP 7.4
2. Run `php artisan route:list`

**Comment by alecritson** [comment]
This should be solved in the current release, looks like #208  was merged
