### ISSUE TITLE
Drafting new product error

### ISSUE THREAD

**Issue by jeanbaptistenguyen** [getcandy/candy-api#223]
## Expected Behavior
Update new draft product normally

## Current Behavior
This error : 
`Argument 1 passed to GetCandy\Api\Core\Products\Drafting\ProductDrafter::firstOrCreate() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in /home/vagrant/code/candy-api/vendor/getcandy/candy-api/src/Http/Controllers/Products/ProductController.php on line 101`

## Possible Solution
When I create a new product and would like to fill information
The line 100 of the class ProductController
` $product = $this->service->findById($id[0], [], false);`
return null instead of an object product which seems normal as the product is still in Draft ?

## Steps to Reproduce
1. Create a new product
2. Fill information
3. Request failed with status code 500 

## Context (Environment)
PHP : 7.2.29
Laravel : 7
Elasticsearch : 6.1.4
MySQL : 5.7.29

## Possible Implementation
I followed the documentation but I feel like I have way too much bug something must be wrong with my environment. Can someone tell me if I have to change version on any of the requirements ?

Thank you !

**Comment by alecritson** [comment]
What version of the hub are you using? [We recently did an update](https://guides.getcandy.io/hub-guides/0.9/introduction/upgrading#upgrading-from-091-to-092) which addressed a few issues with product creation and drafting.

**Comment by alecritson** [comment]
Closing due to original poster not actively working on GetCandy anymore.
