### ISSUE TITLE
Unable to login to hub, API responds with "Call to a member function encodedId() on null""

### ISSUE THREAD

**Issue by daniel-farina** [getcandy/candy-api#227]
Hello,  when logging in to the HUB I encounter the following error:

on endpoint: /api/v1/users/current?includes=roles.permissions,details
```php
{message: "Call to a member function encodedId() on null", exception: "Error",…}
exception: "Error"
file: "/var/www/candy/foodui/vendor/getcandy/candy-api/src/Http/Controllers/Users/UserController.php"
line: 77
message: "Call to a member function encodedId() on null"
trace: [,…]
```
![image](https://user-images.githubusercontent.com/13665117/84586261-e20f7000-ade5-11ea-9d71-78739490e1d8.png)

## Expected Behavior

I should be able to login, I followed this guide: 
https://guides.getcandy.io/getting-started/hub/authentication/#laravel-sanctum

## Possible Solution
Investigating still. 

## Steps to Reproduce
1. Setup GetCandy (Clean install), create user, migrate, seed, etc
2. Follow the this guide https://guides.getcandy.io/getting-started/hub/authentication/#laravel-sanctum
3. Setup the hub, configure your .env
4. try to login.

**Comment by alecritson** [comment]
How have you got all your routes set up?

**Comment by daniel-farina** [comment]
> How have you got all your routes set up?

```

Route::post('/sanctum/token', function(Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required'
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return [
        'token_type' => 'Bearer',
        'access_token' => $user->createToken('hub')->plainTextToken // token name you can choose for your self or leave blank if you like to
    ];
});


Route::post('/login', function (Request $request) {
    if (Auth::attempt([
        'email' => $request->email,
        'password' => $request->password
    ])) {
        return response()->json('', 204);
    }
    return response()->json([
        'error' => 'invalid_credentials'
    ], 403);
});

```


Another interesting fact is that if I enter an invalid user it actually returns 403

![image](https://user-images.githubusercontent.com/13665117/84591032-45f76000-ae09-11ea-83ce-7ba4c4153866.png)

but when I try to login with the correct user, it then returns that weird error message. 

Call to a member function encodedId() on null

It seems it has to do with roles & permissions.

**Comment by daniel-farina** [comment]
Also, 

It the table role_has_permissions table supposed to have anything?, it's currently empty and I don't see any seeds for it.  My user was created during the setup and I see it in the DB.

**Comment by alecritson** [comment]
The `'/sanctum/token'` route I assume is from the other issue, which is not how we would recommend on doing authentication.

Where have you placed `GetCandy::routes()`? In your route service provider? Also can you confirm your hub env variables for:

`AUTH_LOGIN_ENDPOINT` and `AUTH_USER_ENDPOINT`

**Comment by selivanit** [comment]
> Hello, when logging in to the HUB I encounter the following error:
> 
> on endpoint: /api/v1/users/current?includes=roles.permissions,details
> 
> ```
> {message: "Call to a member function encodedId() on null", exception: "Error",…}
> exception: "Error"
> file: "/var/www/candy/foodui/vendor/getcandy/candy-api/src/Http/Controllers/Users/UserController.php"
> line: 77
> message: "Call to a member function encodedId() on null"
> trace: [,…]
> ```
> 
> ![image](https://user-images.githubusercontent.com/13665117/84586261-e20f7000-ade5-11ea-9d71-78739490e1d8.png)
> 
> ## Expected Behavior
> I should be able to login, I followed this guide:
> https://guides.getcandy.io/getting-started/hub/authentication/#laravel-sanctum
> 
> ## Possible Solution
> Investigating still.
> 
> ## Steps to Reproduce
> 1. Setup GetCandy (Clean install), create user, migrate, seed, etc
> 2. Follow the this guide https://guides.getcandy.io/getting-started/hub/authentication/#laravel-sanctum
> 3. Setup the hub, configure your .env
> 4. try to login.

The same situation. Trying to solve it, but without result. Some news?

**Comment by Repox** [comment]
Hi @selivanit 

Could you possibly try and [watch this video I made](https://youtu.be/MtI42iZ3Zfc)?

It's a realtime paced video with instructions that follow the GetCandy guides to get a working environment up and running with both the API and the Admin Hub. Maybe it can reflect if you did something the guides didn't anticipate.

**Comment by selivanit** [comment]
> Hi @selivanit
> 
> Could you possibly try and [watch this video I made](https://youtu.be/MtI42iZ3Zfc)?
> 
> It's a realtime paced video with instructions that follow the GetCandy guides to get a working environment up and running with both the API and the Admin Hub. Maybe it can reflect if you did something the guides didn't anticipate.

Thanks for your response and help!)
The problem was in GetCandy::routes()

I placed this method in routes/api.php, but when I removes it to RouteServiceProvider->map() (before calling mapApiRoutes() and mapWebRoutes()) all become working fine.

**Comment by jeanbaptistenguyen** [comment]
> Hi @selivanit
> 
> Could you possibly try and [watch this video I made](https://youtu.be/MtI42iZ3Zfc)?
> 
> It's a realtime paced video with instructions that follow the GetCandy guides to get a working environment up and running with both the API and the Admin Hub. Maybe it can reflect if you did something the guides didn't anticipate.

Thanks for your video I have the same error with the new Product draft any idea why ?

**Comment by Repox** [comment]
> Thanks for your video I have the same error with the new Product draft any idea why ?

I think the product draft has a bug at the moment. I'll look into it and maybe create a relevant issue.

**Comment by Repox** [comment]
I just tested the drafts on the develop branch, and the issue seems fixed, so I think that you will have the issue resolved with the next release. Maybe @alecritson can come up with an expected time for the next release.

**Comment by alecritson** [comment]
Thanks for your input on this @Repox since this bug is breaking things for people putting the routes in the `api.php` file I'll get a release tagged now.

**Comment by Repox** [comment]
@jeanbaptistenguyen Did you check the drafts with the latest release?

**Comment by jeanbaptistenguyen** [comment]
@Repox I understand that its a open source project still on beta and cant expect much from it but I debugged too much things already. And dont know if I want to keep going. I might wait for the V1 to be released to come back.
I appreciate all your supports and dedication to this great project guys.

**Comment by Repox** [comment]
@jeanbaptistenguyen Just to be clear, I'm not a part of the project, I'm also a project consumer. I too understand that the project is in beta; the team behind seems dedicated to listen to issues and resolving them and are open for suggestions. 

That being said, I understand that you don't have time for helping develop and evolve a beta-project.

**Comment by alecritson** [comment]
@jeanbaptistenguyen Sorry to hear you're going to give it a miss, hopefully we will see you again the future but completely understand your position. We're working collectively on improving the documentation to make sure it's easy for people to get set up. 

I'll close this issue for now.
