### ISSUE TITLE
category endpoint not working

### ISSUE THREAD

**Issue by sadektouati** [getcandy/candy-api#250]
get request to http://localhost:8000/api/v1/categories should give categories
## Current Behavior
it results in a sql error: `Integrity constraint violation: 1052 Column 'drafted_at' in where clause is ambiguous (SQL: select `categories`.*, (select count(*) from `products` inner join `product_categories` on `products`.`id` = `product_categories`.`product_id` inner join `customer_group_product` on `products`.`id` = `customer_group_product`.`product_id` and .....`

**Comment by samundra** [comment]
I also have the same issue.

endpoint that returns this error is : **GET /api/v1/categories`**

**Context:** Trying to list categories as authenticated users returns this error.


```
<!doctype html>
<html class="theme-light">
<!--
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'drafted_at' in where clause is ambiguous (SQL: select `categories`.*, (select count(*) from `products` inner join `product_categories` on `products`.`id` = `product_categories`.`product_id` inner join `customer_group_product` on `products`.`id` = `customer_group_product`.`product_id` and `customer_group_product`.`customer_group_id` in (1) and `customer_group_product`.`visible` = 1 inner join `channel_product` on `products`.`id` = `channel_product`.`product_id` and `channel_product`.`channel_id` = 1 and `channel_product`.`published_at` <= 2020-07-25 17:19:00 where `categories`.`id` = `product_categories`.`category_id` and `products`.`drafted_at` is null and `products`.`deleted_at` is null group by `channel_product`.`product_id`) as `products_count`, (select count(*) from `categories` as `laravel_reserved_0` where `categories`.`id` = `laravel_reserved_0`.`parent_id`) as `children_count`, (select count(1) - 1 from `categories` as `_d` inner join `category_channel` on `categories`.`id` = `category_channel`.`category_id` and `category_channel`.`channel_id` = 1 and `category_channel`.`published_at` <= 2020-07-25 17:19:00 inner join `category_customer_group` on `categories`.`id` = `category_customer_group`.`category_id` and `category_customer_group`.`customer_group_id` in (1) and `category_customer_group`.`visible` = 1 where (`drafted_at` is null and `categories`.`_lft` between `_d`.`_lft` and `_d`.`_rgt`) and `categories`.`drafted_at` is null group by `category_channel`.`category_id`) as `depth` from `categories` inner join `category_channel` on `categories`.`id` = `category_channel`.`category_id` and `category_channel`.`channel_id` = 1 and `category_channel`.`published_at` <= 2020-07-25 17:19:00 inner join `category_customer_group` on `categories`.`id` = `category_customer_group`.`category_id` and `category_customer_group`.`customer_group_id` in (1) and `category_customer_group`.`visible` = 1 where `categories`.`drafted_at` is null group by `categories`.`id`, `category_channel`.`category_id` having `depth` <= 0 order by `_lft` asc) in file /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671

#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('select `categor...', Array, Object(Closure))
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Connection->run('select `categor...', Array, Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2205): Illuminate\Database\Connection->select('select `categor...', Array, true)
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2193): Illuminate\Database\Query\Builder->runSelect()
#4 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2688): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()-->
			</body>

</html>
```

**Comment by darkshifty** [comment]
I have had the same problem in get and post requests on that endpoint, changing mysql strict mode to false in both mysql and config/database.php resolves the issue.

**Comment by darkshifty** [comment]
here is a full stack trace https://flareapp.io/share/LPdWgvmO

**Comment by darkshifty** [comment]
here is a full stack trace https://flareapp.io/share/LPdWgvmO

**Comment by alecritson** [comment]
Can you try the develop branch to see if that solves the issue?

**Comment by darkshifty** [comment]
I'm having trouble getting the routes up in the development branch, is there something new I missed?

The following lines are added to the map function of the RouteServiceProvider.php
`GetCandy::routes([
      'prefix' => 'api/v1'
]);`

**Comment by alecritson** [comment]
Ah try GetCandy::router() :) we will be documenting changes when we tag the release

**Comment by darkshifty** [comment]
Cheers that worked. However, I'm not sure if this is caused by my MySQL version (MariaDB 10.5) but the following error is thrown https://flareapp.io/share/q5Yn2jmX SQL strict is false and SQL mode is empty.

**Comment by alecritson** [comment]
Looks like you’re missing some tables, have you tried running migrate?

**Comment by darkshifty** [comment]
No, i expected the same but the tables are there. The query seems to cause this error. When I run it within a database explorer it results in the same (note that adding categories works fine and updates the database with a new row). I will try setting up MySQL 5.7 and give a update here once i've tested it.

**Comment by darkshifty** [comment]
With MySQL 5.7 https://flareapp.io/share/bP9VEL7Q the same error appears.

**Comment by alecritson** [comment]
Somethings definitely not right, are you sure the right database is being referenced in the `.env` file and the tables exist? I can't think what it could be 🤔

**Comment by darkshifty** [comment]
Same here, I'm clueless... I've created a SQLFiddle which gives the same result http://sqlfiddle.com/#!9/6a2274/1

**Comment by alecritson** [comment]
I appreciate this is an old issue, but this should be sorted in `0.12` so if after upgrading it's still an issue please re open.
