### ISSUE TITLE
Official Doc need to mention php extension php-gmp as php extension

### ISSUE THREAD

**Issue by samundra** [getcandy/candy-api#251]
Currently, installation works fine but while trying to use query endoint `/api/v1/users` we get error which is related to hashids as mentioned here https://github.com/vinkla/hashids/issues/104

## Expected Behavior
- List available users without error

## Current Behavior
- returns error that says we need to install Math extension.

## Possible Solution
Update current documentation and specify that for php along with others we also need to install php-gmp extension as one of the requirement.

## Steps to Reproduce
Install php as regular process. It install fine.
1. Perform GET `api/v1/users` It will return error as "Missing BC Math or GMP extension"

## Context (Environment)
I completed the setup inside docker. Everything was installed as instructed and then visited the said endpoint `api/v1/users`

## Possible Implementation
Update current documentation and specify that we need to install php-gmp extension in php server. Also provide some instruction on how to do it in dockerized environment. 

I used following listed code to install php-gmp inside dockerized environment.

```
    apt-get -y install libgmp-dev && docker-php-ext-install gmp
```

**Comment by alecritson** [comment]
Thanks for the heads up! we'll look to get this into the docs asap.
