### ISSUE TITLE
Addresses v1

### ISSUE THREAD

**Issue by glennjacobs** [getcandy/candy-api#256]
- [ ] Does the endpoint make sense in its context? i.e. `assets/...` not `images/...` or `asset/...`
- [ ] Code design
- [ ] Are the necessary user restrictions in place? i.e. Should this be locked to users with a certain role
- [ ] Anything fundamentally wrong with the approach?
- [ ] Is there anything that could cause a bottleneck or otherwise have a significant impact on performance when scaled?
- [ ] Are we using Eloquent resources on returned data when available?
- [ ] Validation
- [ ] Automated testing

**Comment by glennjacobs** [comment]
Notes from an initial review...

- Do we want to include salutation so that customer services know how someone wishes to be addressed? Probably. In which case, we'll need a list of them I guess.
- Not sure we need both "county" and "state" fields, they're essentially the same thing. Perhaps change to "region"?
- As we know, some payment gateways such as SagePay require the USA State code and it has to be accurate. This may well be the same for other countries. Shall we include another endpoint for "regions" that relate to countries?
- "zip" should probably be named "postal_code", as "zip" is very much specific to the USA.
- Do we want to include some sort of "notes" or "comments" field? Helpful for including delivery instructions.
- "country" is listed before "zip" in the table fields, might want to get it in a logical order.
- Should we be storing the country name, or rather the Country ID as a relationship?
- Some addresses will be for companies, so we should include a Company Name field.
- Do we want to allow for other data to be saved against an address? Perhaps a generic meta field using JSON?
- Do we want to include a telephone field, as often couriers will want a telephone stored for delivery assistance?

**Comment by alecritson** [comment]
I think they're all valid points. 

> Shall we include another endpoint for "regions" that relate to countries? 

How do you imagine this tying in with Addresses?

> Should we be storing the country name, or rather the Country ID as a relationship?
I'm not against storing the country id. It's unlikely to cause issues and keeps things in tidy.

**Comment by glennjacobs** [comment]
Having just used Amazon, I like the idea of being able to tell which addresses have been recently used.

**Comment by glennjacobs** [comment]
We can reference FedEx etc to see what the standard address field naming is.

**Comment by glennjacobs** [comment]
Store Country ISO_2 code against addresses as added bonus.

**Comment by glennjacobs** [comment]
We won't worry about a state/county lookup just yet. Not sure where data would come from.

**Comment by glennjacobs** [comment]
We should call the notes field 'delivery_instructions'.
