### ISSUE TITLE
issue with installation   " Cannot redeclare GetCandy\Api\Core\Orders\Models\Order::scopePlaced()" using laravel 7

### ISSUE THREAD

**Issue by awacris** [getcandy/candy-api#309]
Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Cannot redeclare GetCandy\Api\Core\Orders\Models\Order::scopePlaced() in C:\wamp\www\ecomerceapi\vendor\getcandy\candy-api\src\Core\Orders\Models\Order.php on line 81

   Symfony\Component\ErrorHandler\Error\FatalError

  Cannot redeclare GetCandy\Api\Core\Orders\Models\Order::scopePlaced()

  at C:\wamp\www\ecomerceapi\vendor\getcandy\candy-api\src\Core\Orders\Models\Order.php:81
    77|      *
    78|      * @param Builder $qb
    79|      * @return Builder
    80|      */
  > 81|     public function scopePlaced($qb)
    82|     {
    83|         return $qb->whereNotNull('placed_at');
    84|     }
    85|

   Whoops\Exception\ErrorException

  Cannot redeclare GetCandy\Api\Core\Orders\Models\Order::scopePlaced()

  at C:\wamp\www\ecomerceapi\vendor\getcandy\candy-api\src\Core\Orders\Models\Order.php:81
    77|      *
    78|      * @param Builder $qb
    79|      * @return Builder
    80|      */
  > 81|     public function scopePlaced($qb)
    82|     {
    83|         return $qb->whereNotNull('placed_at');
    84|     }
    85|

  1   C:\wamp\www\ecomerceapi\vendor\filp\whoops\src\Whoops\Run.php:408
      Whoops\Run::handleError("Cannot redeclare GetCandy\Api\Core\Orders\Models\Order::scopePlaced()", "C:\wamp\www\ecomerceapi\vendor\getcandy\candy-api\src\Core\Orders\Models\Order.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json to its original content.

**Comment by awacris** [comment]
for anyone who has same problem this function was declared twice just comment out one of the and you are good to go.

 /**
     * Define the placed scope.
     *
     * @param Builder $qb
     * @return Builder
     */
    public function scopePlaced($qb)
    {
        return $qb->whereNotNull('placed_at');
    }

**Comment by glennjacobs** [comment]
Which branch/version was this on? Thx

**Comment by awacris** [comment]
not sure which was just did composer required as from the documentation.
composer require getcandy/candy-api:^0.9-beta

**Comment by alecritson** [comment]
I've been able to do a clean install on Laravel 8 on `0.10.1-beta` please update to this version.
