### ISSUE TITLE
Question - What will be the feature for V1 ?

### ISSUE THREAD

**Issue by lilouch** [getcandy/candy-api#310]
Hi,

I came accross your solution for building an ecommerce. I need to buil a ecomerce store and I like your approach.
However, I would like to know
- If the V1 will change a lot of things on the spec ?
- what would be the next features ?

Thank in advance,
Lirone

**Comment by glennjacobs** [comment]
v1 will not be changing the API spec much, so it wouldn't take much to upgrade I'd suggest.

Once we have v1 launched we'll be making a public roadmap available. So I can't comment on that right now. However, we anticipate buiding plenty of addons for things like payment providers, shipping, discount types, etc etc. Lots of big plans.

**Comment by lilouch** [comment]
When do you plan to release this version by the way ?

**Comment by glennjacobs** [comment]
Sorry, it's pencilled in for November this year.

**Comment by lilouch** [comment]
Ok thank you ! Looking forward !
