### ISSUE TITLE
sanctum login cors issue

### ISSUE THREAD

**Issue by awacris** [getcandy/candy-api#311]
having issues with authentication first having this error when i add sanctum configuration to routeServiceProvider.

  Call to undefined method GetCandy\Api\Core\RouteRegistrar::auth()

  at C:\wamp\www\Ecommerce\ecommerceApi\app\Providers\RouteServiceProvider.php:52
    48|         ], function ($registrar) {
    49|             Route::group([
    50|                  'middleware' => ['auth:sanctum', 'api']
    51|             ], function () use ($registrar) {
  > 52|                 $registrar->auth();
    53|             });
    54|             Route::group([
    55|                 'middleware' => ['api']
    56|             ], function () use ($registrar) {

  1   C:\wamp\www\Ecommerce\ecommerceApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:415
      App\Providers\RouteServiceProvider::App\Providers\{closure}(Object(Illuminate\Routing\Router))

  2   C:\wamp\www\Ecommerce\ecommerceApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:374
      Illuminate\Routing\Router::loadRoutes(Object(Closure))

secondly
also without that config and only this 
 GetCandy::routes([
        'prefix' => 'api/v1'
    ]); 
i get following  CORS errors

Access to XMLHttpRequest at 'http://127.0.0.1/api/v1/sanctum/csrf-cookie' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

My Setup (locally no docker container)
sanctum install 
sanctum config
 'stateful' => explode(',', env('SANCTUM_STATEFUL_DOMAINS', 'localhost:3000, localhost, 127.0.0.1,127.0.0.1:3000,127.0.0.1,127.0.0.1:8000,::1')),
'prefix' => 'api/v1/sanctum',

cors config 
    'supports_credentials' => true,

env config
SESSION_DRIVER=cookie
SESSION_DOMAIN default null in session config

nothing changed in the nuxt side.
any help please

**Comment by alecritson** [comment]
are you running your laravel app with `php artisan serve --host=localhost` ?

**Comment by awacris** [comment]
I didn't include the host tag artisan serve so it's running on localhost at
127.0.0.1:8000 Which I configure in the. env file of the hub

**Comment by alecritson** [comment]
This is more of a sanctum issue rather than a GetCandy one. You need to make sure your laravel app is running on the same domain as the hub. Also check the updated guides and make sure all steps have been taken.

https://guides.getcandy.io/getting-started/installation#sanctum-configuration

Closing this for now but if you feel there is an issue with GetCandy, feel free to re open :)
