### ISSUE TITLE
v10 installation issues

### ISSUE THREAD

**Issue by awacris** [getcandy/candy-api#312]
after unsuccessful with v9 tried v10 with a fresh install of laravel 8 but getting this issues
Problem 1
    - Can only install one of: laravel/framework[v8.6.0, 7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v8.6.0].
    - Can only install one of: laravel/framework[7.x-dev, v8.6.0].
    - neondigital/laravel-versioning dev-master requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - getcandy/candy-api 0.10.0-beta requires neondigital/laravel-versioning dev-master -> satisfiable by neondigital/laravel-versioning[dev-master].
    - Installation request for getcandy/candy-api 0.10-beta -> satisfiable by getcandy/candy-api[0.10.0-beta].
    - Installation request for laravel/framework (locked at v8.6.0, required as ^8.0) -> satisfiable by laravel/framework[v8.6.0].
  

## Steps to Reproduce

1.
2.
3.
4.

**Comment by alecritson** [comment]
This was the result of a version constraint on a third party package, can you try again as it should be sorted now.

**Comment by awacris** [comment]
thanks it installed successfully but the issue is with mapping the candy routes laravel 8 has a new structure for the RouteServiceProvider  file when I include the candy routes there, I'm getting an error tried to use the old map method as in the documentation still have an error here is the error

   GetCandy\Api\Exceptions\InvalidServiceException

  Service "routes" doesn't exist

  at C:\wamp\www\Ecommerce\ecommerce_api\vendor\getcandy\candy-api\src\Core\GetCandy.php:145
    141▕             $resolvingName = Str::snake($name);
    142▕
    143▕             return app("getcandy.{$resolvingName}");
    144▕         } catch (\Exception $e) {
  ➜ 145▕             throw new InvalidServiceException("Service \"{$name}\" doesn't exist");
    146▕         }
    147▕     }
    148▕ }
    149▕

  1   C:\wamp\www\Ecommerce\ecommerce_api\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
      GetCandy\Api\Core\GetCandy::__call("routes")

  2   C:\wamp\www\Ecommerce\ecommerce_api\routes\api.php:22
      Illuminate\Support\Facades\Facade::__callStatic("routes")

please can you direct me to what the issue might be

**Comment by alecritson** [comment]
Try `GetCandy::router()` instead of `GetCandy::routes()` i'll get the docs updated.

**Comment by awacris** [comment]
Thanks  that worked then running candy:install gives the following error for elastic search, don't know if there is a config i'm missing.

  Argument 1 passed to Elastica\Client::__construct() must be of the type array, null given, called in C:\wamp\www\Ecommerce\ecommerce_api\vendor\getcandy\candy-api\src\Installer\Runners\PreflightRunner.php on line 30

  at C:\wamp\www\Ecommerce\ecommerce_api\vendor\ruflin\elastica\lib\Elastica\Client.php:87
     83▕      * @param array           $config   OPTIONAL Additional config options
     84▕      * @param callback        $callback OPTIONAL Callback function which can be used to be notified about errors (for example connection down)
     85▕      * @param LoggerInterface $logger
     86▕      */
  ➜  87▕     public function __construct(array $config = [], $callback = null, LoggerInterface $logger = null)
     88▕     {
     89▕         $this->_callback = $callback;
     90▕
     91▕         if (!$logger && isset($config['log']) && $config['log']) {

  1   C:\wamp\www\Ecommerce\ecommerce_api\vendor\getcandy\candy-api\src\Installer\Runners\PreflightRunner.php:30
      Elastica\Client::__construct()

  2   C:\wamp\www\Ecommerce\ecommerce_api\vendor\getcandy\candy-api\src\Installer\GetCandyInstaller.php:78
      GetCandy\Api\Installer\Runners\PreflightRunner::run()

**Comment by alecritson** [comment]
What version of Elastisearch do you have installed? Needs to be ~6.8
