### ISSUE TITLE
Error running php artisan candy:search:index

### ISSUE THREAD

**Issue by palfaro91** [getcandy/candy-api#317]
## Expected Behavior

Running  php artisan candy:search:index should work out of the box
## Current Behavior

When I run the php artisan candy:search:index command I get this error

Illuminate\Contracts\Container\BindingResolutionException 

Target class [GetCandy\Api\Core\Languages\Services\LanguageService] does not exist.

## Steps to Reproduce

1. Create new laravel project
2. Install getcandy
3. run php artisan candy:search:index

I'm running on Laravel 8.11.2 and getcandy 0.10.1-beta

**Comment by brycelarge** [comment]
I'm also having that issue. There is no sub directory in the Languages directory called "Services"

I tried searching for a class called LanguageService but also did not find anything

**Comment by alecritson** [comment]
If possible can you try on the develop branch `dev-develop` and see if that fixes your issue?

**Comment by brycelarge** [comment]
> If possible can you try on the develop branch `dev-develop` and see if that fixes your issue?

Yip that fixed the issue

**Comment by alecritson** [comment]
The getcandy hub composer package is archived at this point so wouldn't recommend using it. This issue should be sorted on release [0.10.2-beta](https://github.com/getcandy/candy-api/releases/tag/0.10.2-beta)
