### ISSUE TITLE
Error accessing /products endpoint

### ISSUE THREAD

**Issue by palfaro91** [getcandy/candy-api#318]
Hello, I'm getting an error accessing the `/products` endpoint. It returns a sql error that says the id column already exists. It looks like is selecting `product.*` twice
## Expected Behavior

Accessing the /products endpoint should return a list of products
## Current Behavior

SQL error is being thrown when accessing the `/products` endpoint
```SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (SQL: select count(*) as aggregate from (select `products`.*, `products`.* from \`products\` inner join `customer_group_product` on `products`.`id` = `customer_group_product`.`product_id` and `customer_group_product`.`customer_group_id` in (1) and `customer_group_product`.`visible` = 1 inner join `channel_product` on `products`.`id` = `channel_product`.`product_id` and `channel_product`.`channel_id` = 1 and date(`channel_product`.`published_at`) <= 2020-10-22 where `products`.`drafted_at` is null and `products`.`deleted_at` is null group by `channel_product`.`product_id`) as `aggregate_table`)```

## Steps to Reproduce

1. Run project
2. Access 127.0.0.1:8001/api/v1/products

**Comment by alecritson** [comment]
We know what's causing this and hopefully we'll have a fix up soon 💪

**Comment by alecritson** [comment]
This should be fixed from `0.11.2`
