### ISSUE TITLE
php artisan candy:install broken with composer version 2

### ISSUE THREAD

**Issue by brycelarge** [getcandy/candy-api#320]
GetCandy\Api\Core\GetCandy::version is trying to obtain the candy version from vendor/composer/installed.json

The structure of installed.json file has changed in version 2.

I got passed the error with this:

// Composer version 2 support
$packageManifest = json_decode(File::get(base_path('vendor/composer/installed.json')));
$packages = is_array($packageManifest) ? collect($packageManifest) : collect($packageManifest->packages);

Not sure if that is backward compatible but could be.

**Comment by onurkose** [comment]
It'll still be broken if you use Laravel 8, but this one #322 for Composer 2 support.

**Comment by brycelarge** [comment]
> It'll still be broken if you use Laravel 8, but this one #322 for Composer 2 support.

Your PR came 5 hours after my PR
