### ISSUE TITLE
PluginCollection and PluginResource do not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by ven7ura** [getcandy/candy-api#349]
Clean laravel and getcandy/candy-api installation and get a warning that some files does not comply with psr-4.
## Expected Behavior

There should be no warnings.
## Current Behavior

`> composer update getcandy/candy-api`
`Loading composer repositories with package information`
`Updating dependencies`
`Nothing to modify in lock file`
`Installing dependencies from lock file (including require-dev)`
`Nothing to install, update or remove`
`Package paypal/rest-api-sdk-php is abandoned, you should avoid using it. No replacement was suggested.`
`Generating optimized autoload files`
`Class GetCandy\Api\Http\Resources\Payments\PluginCollection located in ./vendor/getcandy/candy-api/src/Http/Resources/Plugins/PluginCollection.php does not comply with psr-4 autoloading standard. Skipping.`
`Class GetCandy\Api\Http\Resources\Payments\PluginResource located in ./vendor/getcandy/candy-api/src/Http/Resources/Plugins/PluginResource.php does not comply with psr-4 autoloading standard. Skipping.`
## Steps to Reproduce

1. Install Laravel with installer
2. composer require the package
3. or composer update 

## Context (Environment)

Using Windows 10 wsl2 Ubuntu 20.04
## Detailed Description

First time using the package and see this warning.

**Comment by alecritson** [comment]
Thanks for this, will be sorted in `0.11.4`

**Comment by alecritson** [comment]
This should now be resolved.
