### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by devkomtorg** [getcandy/candy-api#38]
## Current Behavior
cURL error 60: SSL certificate problem: unable to get local issuer certificate
## Steps to Reproduce

1. I'd downloaded file cacert.pem into c:/openserver/modules/php/PHP-7.1/extras/ssl

2. My php.ini:

[curl]
curl.cainfo = "c:/openserver/modules/php/PHP-7.1/extras/ssl/cacert.pem"

3. Then I restarted Open Server

4.

**Comment by alecritson** [comment]
This looks like an issue with your set up and not an issue with GetCandy, see this:

https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate
