### ISSUE TITLE
exceptions.invalid_service (View: /var/www/online-store/vendor/getcandy/candy-hub/resources/views/layout.blade.php)

### ISSUE THREAD

**Issue by noud** [getcandy/candy-api#383]
**Describe the bug**
I did a 'normal' install in laradock.
Then if i go to hub and login after that i get

GetCandy\Api\Exceptions\InvalidServiceException
exceptions.invalid_service (View: /var/www/online-store/vendor/getcandy/candy-hub/resources/views/layout.blade.php)

**Comment by glennjacobs** [comment]
It looks like you're trying to use the old Laravel Hub. Unfortunately, that is no longer supported.

**Comment by noud** [comment]
what should i use then?

**Comment by glennjacobs** [comment]
The hub has been moved out of Laravel, and into a separate NuxtJS app. See the guides on the website for more information.
