### ISSUE TITLE
storefront error

### ISSUE THREAD

**Issue by guilhermejuniorjuk** [getcandy/candy-api#40]
URL: http://candy.localhost.

`Client error: `POST http://candy.localhost/oauth/token` resulted in a `401 Unauthorized` response: {"error":"invalid_client","message":"Client authentication failed"} (View: C:\wamp64\www\candy\resources\views\_layouts\base.blade.php) (View: C:\wamp64\www\candy\resources\views\_layouts\base.blade.php)`

Solution?

**Comment by alecritson** [comment]
Looks like you're either not passing the client credentials or they are incorrect, see passport docs

https://laravel.com/docs/5.6/passport#requesting-password-grant-tokens

**Comment by guilhermejuniorjuk** [comment]
solved! thanks
