### ISSUE TITLE
Unauthenticated after successful login

### ISSUE THREAD

**Issue by nicholaspearson** [getcandy/candy-api#409]
**Describe the bug**
Hitting: api/v1/users/current?include=customer.customerGroups,roles.permissions results in "Unauthenticated" after a successful login.

Response from login:
/api/login
Request Method: POST
Status Code: 204 

Admin Hub: admin.domain.com
API: api.domain.com

**To Reproduce**
 - Install as per api installation guide - ensure you use the boiler project

**Expected behavior**
Login to the hub successfully.

**Screenshots**
![Screenshot 2021-07-28 at 01 55 01](https://user-images.githubusercontent.com/9952461/127246279-b9256ed9-1f19-4725-bbd7-5def3cf54335.png)

**Comment by nicholaspearson** [comment]
Also, followed the FAQ's SESSION_DRIVER is cookie as per https://docs.getcandy.io/hub/getting-started/troubleshooting.html#the-api-just-returns-unauthenticated

**Comment by xaniuskarlhall** [comment]
Getting the same error as well sigh...

**Comment by xaniuskarlhall** [comment]
@nicholaspearson did you find a solution?

**Comment by alecritson** [comment]
Getting an unauthenticated error does sound like a CORS issue. Are you ensuring that both the api and hub are running off the same TLD?

**Comment by ThyrithSor** [comment]
I fixed this issue by adding the following line to `api` attribute inside `$middlewareGroups`:
```php
\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
```
Ref: https://laravel.com/docs/8.x/sanctum#installation

**Comment by alecritson** [comment]
Glad you got it sorted. Will close this issue as it looks resolved.
