### ISSUE TITLE
API client not initiliazed?

### ISSUE THREAD

**Issue by tooshay** [getcandy/candy-api#47]
Following the examples in the candy-store, I'm attempting to create a user using the API client. Using the new facade name (CandyClient) instead of the old one (GetCandyClient), the client is failing when trying to requestToken:

```
private function requestToken($params)
    {
        try {
            $response = $this->client->post('oauth/token', [    // <---- HERE
                'form_params' => array_merge(
                    [
                        'client_id' => $this->getClientId(),
                        'client_secret' => $this->getClientSecret()
                    ],
                    $params
                ),
                'verify' => config('services.ecommerce_api.verify'),
            ]);
        } catch (ClientException $e) {
            return new ApiResponse($e->getResponse());
        }
        return new ApiResponse($response);
    }
```
...complaining that `$this->client` isn't set. I saw an `init()` in the client's `Candy` class that created the client, but I can't see where this method is called in the store (or anywhere else).

## Steps to Reproduce

1. Create a controller/action
2. Try calling `CandyClient::Customers()->create($customer);` (or anything else)

**Comment by alecritson** [comment]
Hey @tooshay 

You should be able to initialise the client by doing:

```
CandyClient::init({API_BASE_URI}, [
    'client_id' => {CLIENT_ID},
    'client_secret' => {CLIENT_SECRET},
    'locale' => app()->getLocale(),
    'channel' =>{CHANNEL}
]);
```
Documentation for the client is something we're working on.

**Comment by tooshay** [comment]
Where do you advise doing this?

**Comment by alecritson** [comment]
In `AppServiceProvider`'s `boot` method should do the trick.

**Comment by tooshay** [comment]
Yeah, beat you to it by a minute!

It seems to have initialised OK but records still aren't getting created, and I'm seeing no errors. Is there anything else I'd need to do to get the client working?

(note: Sorry for the barrage/nagging; I just need a little guidance to get things set up and going!)

**Comment by alecritson** [comment]
Yeah it might that the customers part of the client is still being refactored, do you get anything if you do:

```
CandyClient::Categories()->get()
```

**Comment by tooshay** [comment]
I'm getting a 404 when making that call in my controller... (my categories table was empty though, so I just created a category and put in some random JSON in the attribs column).

Just to be clear: my goal at this point is to just accept some basic customer data in a form and use the client to register the customer, without logging in or anything. I feel like I'm getting close, but still no cigar.

**Comment by shaunrainer** [comment]
Hi tooshay,
I have pushed fixes to the dev branch for both candy-client-php and candy-api, if you could pull the latest it should fix your 404.

```
CandyClient::Customers()->create([`
    'email' => 'test@user.com',
    'firstname' => 'test',
    'lastname' => 'user',
    'password' => 'password',
    'password_confirmation' => 'password',
    'language' => 'en'
]);
```

Hope this helps :)

**Comment by tooshay** [comment]
Hey @shaunrainer - better, but I still have to disable all of the `Set*****Middelware` calls to get it to work... Any idea why this would happen or how to fix?

```
local.ERROR: Class 'CurrencyConverter' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'CurrencyConverter' not found at /Projects/myShop/vendor/getcandy/candy-api/src/Http/Middleware/SetCurrencyMiddleware.php:19)
[stacktrace]
```

**Comment by alecritson** [comment]
What version of laravel are you using? Does it have package auto discover?

**Comment by tooshay** [comment]
Using 5.6, it sure does!

**Comment by alecritson** [comment]
I think this was related to having GetCandy in the `dont-discover` array in `composer.json` ? I'll close it but if it's still an issue let us know.
