### ISSUE TITLE
Testing the client

### ISSUE THREAD

**Issue by tooshay** [getcandy/candy-api#50]
I'm in the process of writing some preliminary tests for our store and need to mock the CandyClient's behaviour. 

I've spotted the `Client::fake()` method... Can you provide some insight on how to write tests, with maybe an example or two? The more details you can give, the better!

**Comment by alecritson** [comment]
Hey @tooshay 

Sure, so you can set up the client like:

```
CandyClient::fake();
CandyClient::init(config('app.url'));
```
Then you can create a mock response like:

```
$response = new GetCandy\Client\Testing\Response(200, ['some' => 'data']);
CandyClient::next($response);
```
If your service class makes two GetCandy api requests under the hood, you can queue them up:

```
$firstResponse =  new GetCandy\Client\Testing\Response(200, ['some' => 'data']);
$secondResponse = new GetCandy\Client\Testing\Response(200, ['more' => 'data']);
```

Then just call
```
CandyClient::queue([$firstResponse, $secondResponse]);
```

**Comment by tooshay** [comment]
@alecritson This is great, thanks.

I do have some functional tests that require writing to the DB, however, and while the parts of our application that do this write to the test DB when the test runs, CanyAPI still writes to the regular DB. How can I get the API to write to the test one when tests are run?
