### ISSUE TITLE
Elasticsearch free version

### ISSUE THREAD

**Issue by guestisp** [getcandy/candy-api#58]
Any plans or workaround on how to remove elasticsearch ?
what is the purpose of elasticsearch in Candy ?

**Comment by alecritson** [comment]
It's used to search the products/categories. We first looked at Algolia, but thought it was better (being open source) to use an open source search engine. It will be driver based and we will support different providers in the future.

**Comment by guestisp** [comment]
For small shop, won't be possible to use a php-native solution with no external requirements?
If you have less than 1000 products, a simple search on a properly indexed database would be more than enough.

**Comment by glennjacobs** [comment]
The search system is driver based. At the start of the project, we took the decision to use Elasticsearch as it gives the best performance whilst still being open source and free to use. And lots of Laravel developers are familiar with Elasticsearch. It's also pretty easy to install if required.

The search does more than just a simple keyword search. There's filters, aggregations, etc which are quite tricky to produce in MySQL (as it's not a search engine).

However, down the line we imagine a MySQL driver being developed and possibly others too. I would imagine when we get to a beta release it will be looked at in more detail.
