### ISSUE TITLE
Method Illuminate\Database\Query\Builder::assignRole does not exist.

### ISSUE THREAD

**Issue by syamantak** [getcandy/candy-api#67]
I am getting this error after running php artisan candy:install on fresh install where i followed the instructions for candy api and hub.

**Comment by syamantak** [comment]
Oh, i am very sorry. i forgot to add use HasCandy; 
What a silly mistake!!

**Comment by SlavkaDo** [comment]
Hi. 
I'm trying to run candy-store in docker with 3 containers web, db, app. 
I can't login as a user from shop and can't see hub also. 
I can't register neither. I have trait in model and it looks like I have also connection to db. 
Could you help me, where to look for error? I write login info, click login-> something is doing and then redirect to the same page. The same with register.
Thanks
