### ISSUE TITLE
Incorrect trable in Fraud fields migration

### ISSUE THREAD

**Issue by Jamiewarb** [getcandy/candy-api#69]
There is a new database migration for adding Fraud Fields to the Transactions table.

Unfortunately the `down()` function is referencing the `discounts` table instead of the `transactions` table. This is resulting in failed table rollbacks.

_As a side note, the migration also has a 2019 prefix, when it should be 2018?_

https://github.com/getcandy/candy-api/blob/dev/database/migrations/2019_09_24_104330_add_fraud_fields_to_transactions.php

**Comment by alecritson** [comment]
Thanks @Jamiewarb 

This should be fixed now!
