### ISSUE TITLE
cURL error 6

### ISSUE THREAD

**Issue by emmanuelndong** [getcandy/candy-api#71]
cURL error 6: Could not resolve host: candy-store.test (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by alecritson** [comment]
This is a duplicate of #54

**Comment by emmanuelndong** [comment]
Salut j'ai vraiment besoin d'aide pour la configuration voir même
l'installation. Je ne comprend vraiment pas cette notion de passeport.
Merci d'avance

Le lun. 1 oct. 2018 à 19:52, Alec Ritson <notifications@github.com> a
écrit :
