### ISSUE TITLE
Aide pour la configuration

### ISSUE THREAD

**Issue by emmanuelndong** [getcandy/candy-api#73]
Salut j'ai vraiment besoin d'aide pour l'installation et la configuration. Comment faire pour voir la boutique.

**Comment by alecritson** [comment]
Hi @emmanuelndong 

Please can you translate this to english so we can help you

**Comment by emmanuelndong** [comment]
Hi I really need help with the installation and configuration. How to see the shop.

**Comment by alecritson** [comment]
What exactly are you having issues with?

**Comment by emmanuelndong** [comment]
when i do the command php artisan serve and i access to my shop by 
localhost:8000
Client error: `POST http://localhost/oauth/token` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found (truncated...) (View: C:\Users\jorge\Desktop\candy-store\resources\views\_layouts\base.blade.php) (View: C:\Users\jorge\Desktop\candy-store\resources\views\_layouts\base.blade.php)

**Comment by alecritson** [comment]
Okay, what happens when you add the port i.e `http://localhost:8000/oauth/token`

**Comment by emmanuelndong** [comment]
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
No message

**Comment by emmanuelndong** [comment]
Symfony \ Component \ HttpKernel \ Exception \
 MethodNotAllowedHttpException
No message

**Comment by alecritson** [comment]
Did you try that url with a `POST` request or a `GET` request? Try using software like https://insomnia.rest/ to query the API easier

**Comment by alecritson** [comment]
Hey @emmanuelndong 

I'm going to close this for inactivity, if you still have a problem, just reopen the issue.
