### ISSUE TITLE
Candy hub pulling in app.js rather than hub.js

### ISSUE THREAD

**Issue by yasgreen93** [getcandy/candy-api#74]
RE: Whirli (CC @Jamiewarb and @shaunrainer)

## Expected Behavior
From looking at the code here https://github.com/getcandy/candy-hub/blob/dev/resources/views/partials/scripts.blade.php when I load the warehouse page it should load `candy-hub/js/hub.js`.

## Current Behavior

It is trying to load `candy-hub/js/app.js` but getting a 404.

## Steps to Reproduce

1. In the Whirli project, pull down development, `composer install` etc.
2. `php artisan vendor:publish --tag="public"`
3. `php artisan candy:elastic:index`
4. Go to your local whirli environment `/warehouse` and see in the console the error:
`GET https://whirli.local/candy-hub/js/app.js net::ERR_ABORTED 404 (Not Found)`.

## Context (Environment)

Logging into the candy hub warehouse to make progress on the Whirli site.

**Comment by glennjacobs** [comment]
Hi @yasgreen93 

This seems like a Whirli project-specific issue, not something for the GetCandy API.

Also, remember GetCandy is open source, so you may not want to be discussing private projects here.

Would you please open this ticket on your project's repo instead and I'm sure @shaunrainer will take a look.

Best regards
Glenn

**Comment by gRoberts84** [comment]
Negatory - I've just installed a fresh Laravel install and setup API/Hub, nothing else.

public/hub/js only contains hub.js, however the browser is requesting app.js with a 404.

![image](https://user-images.githubusercontent.com/348184/46891514-0624ec00-ce62-11e8-9759-280c887195a3.png)
