### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by bauersfeld** [getcandy/candy-api#75]
## Expected Behavior
Api endpoint calls via hub interface should not return errors

## Current Behavior
Getting '401 Unauthorized' when accessing api endpoint 

## Possible Solution
??

## Steps to Reproduce
Did a fresh install from github

1. git clone https://github.com/getcandy/candy-store.git
2. composer install
3. php artisan vendor:publish --provider="GetCandy\Api\Providers\ApiServiceProvider"
4. php artisan vendor:publish --tag="public"
5. Renamed the .env.example to .env and set database vars
6. php artisan candy:install
7. set .env CANDY_API vars
CANDY_API_URL=http://candy-store.test
CANDY_API_VERIFY=true
CANDY_API_ID=1
CANDY_API_SECRET=ekiUgjvrC4KuxrGfdZLo1WMr6R5Vz0cCCqpqLi6X

## Context (Environment)
Trying to login to http://candy-store.test/hub and I'm successful except for all http://candy-store.test/api calls are being rejected with a 401 error and the interface features are not useable.  Example of api calls generating 401 errors from browser console
 
http://candy-store.test/api/v1/channels
http://candy-store.test/api/v1/taxes
http://candy-store.test/api/v1/languages

**Comment by alecritson** [comment]
Hey @bauersfeld 

Just a stretch, if you look at the console in the hub, on one of the requests do you see something like an encryption exception? or something similar.

**Comment by bauersfeld** [comment]
No exceptions.  I get this response for each of the api's

`{"error":"Unauthenticated."}`

I'm not running Valet with Elastic, could that be a problem? Are the steps I outlined about the everything needed for the install?

Thx

**Comment by alecritson** [comment]
Yeah it just looks like the token isn't being passed through the axios calls in the hub, which is strange. What set up are you using? Vagrant?

**Comment by bauersfeld** [comment]
No, I'm using MAMP.  Any thoughts on what I can do to resolve?

**Comment by alecritson** [comment]
I'm not entirely sure yet tbh, might need a bit more info.

On the requests in the hub, if you check one is there a token being passed in the headers?

**Comment by bauersfeld** [comment]
Here is a screen shot of the network requests after I signin to the hub
![image](https://user-images.githubusercontent.com/552318/46840620-f342e680-cd91-11e8-8f12-15a92eb0ad1f.png)

**Comment by gRoberts84** [comment]
FYI, I'm able to replicate this on a fresh install using Valet+.

- composer create-project --prefer-dist laravel/laravel candy "5.6.*"
- cd candy
- composer require paragonie/random_compat:2.* (random v9.99.99 issue if I don't do this)
- composer require getcandy/candy-api
- composer require getcandy/candy-hub (this didn't install API as docs suggested)
- php artisan vendor:publish --tag=public
- php artisan vendor:publish --tag=config
- setup .env
- php artisan candy:install

Seems like all XHR requests do not contain any tokens etc?

**Comment by information-security** [comment]
Hi,

Any updates or possible workarounds on this? I can reproduce this bug as well.

**Comment by information-security** [comment]
FYI, I tried to use dev branch of candy-api with candy-store and apart from a problem I had with HasCandy that I had to change
`use GetCandy\Api\Traits\HasCandy;`
to
`use GetCandy\Api\Core\Traits\HasCandy;`
in app/User.php file, the 401 Unauthorized problem is gone.

**Comment by alecritson** [comment]
@information-security seems to have found a solution, if the problem persists, reopen the issue.

**Comment by mcmc4519** [comment]
Have same problem on branch **master**, when I change.
`use GetCandy\Api\Traits\HasCandy;`
to
`use GetCandy\Api\Core\Traits\HasCandy;`

I have error: `Trait 'GetCandy\Api\Core\Traits\HasCandy' not found`

**Comment by alecritson** [comment]
Yeah `use GetCandy\Api\Core\Traits\HasCandy;` is for the dev branch

**Comment by mcmc4519** [comment]
> Yeah `use GetCandy\Api\Core\Traits\HasCandy;` is for the dev branch

Thank for comment!

Can I resolve this problem in master?
