### ISSUE TITLE
BasketController@update route, method non-existant

### ISSUE THREAD

**Issue by Jamiewarb** [getcandy/candy-api#77]
Afternoon guys 👋 

So, the route `api/v1/baskets/saved/{basket}` is defined in routes/api.client.php, at line 45, the method it calls (`BasketController@update`) has no implementation. Is it possible it is missing, or that it shouldn't have been defined in the first place? 

It seems `@store` is doing the PUT behaviour instead, but by passing the ID in the request under the key `basket_id`.

Just wanted to check this is intentional, and not accidentally missed?

## Context (Environment)
I'm looking to create and then update a basket, and wasn't clear the routine based on these methods.

Currently I seem to have to do the following:

```php
// Create an empty basket for a user
CandyClient::Basket()->Update([
    'user' => 'l8mabw7w',
]);

// Create a basket for a user with products in it
CandyClient::Basket()->Update([
    'user' => 'l8mabw7w',
    'variants' => [
        [
            'id' => 'lmawh7sd',
            'quantity' => 1,
        ],
    ],
]);

// Update an existing basket to set different products
CandyClient::Basket()->Update([
    'basket_id' => '24lpwzf2',
    'variants' => [
        [
            'id' => '7ujjyans',
            'quantity' => 2,
        ],
    ],
]);
```

Does this seem correct? The above all uses the `@store` method on BasketController, rather than the last one using `@update`, which I would have expected it to use.

Cheers!

**Comment by alecritson** [comment]
Hey @Jamiewarb 

If you look at the definition in the routes file [here](https://github.com/getcandy/candy-api/blob/dev/routes/api.php#L69) It actually refers to [this controller and method](https://github.com/getcandy/candy-api/blob/dev/src/Http/Controllers/Baskets/SavedBasketController.php#L18)

[I couldn't find that definition in `routes/api.client.php` anywhere](https://github.com/getcandy/candy-api/blob/dev/routes/api.client.php#L45)

This actually refers to when a user is logged in and they have a basket they want to save, maybe to reuse at a later date without having to add everything in again. 

If I'm wrong, please reopen :)

**Comment by Jamiewarb** [comment]
Hey Alec,

Thanks for the response.

The definition is indeed in [`routes/api.client.php`](https://github.com/getcandy/candy-api/blob/dev/routes/api.client.php#L45), on line 45:


```php
$router->resource('baskets', 'Baskets\BasketController', [
    'except' => ['edit', 'create', 'destroy'],
]);
```

The resource is created, which is creating the store method.

Running `php artisan route:list | grep BasketController@store` will show you this route, and the undefined store method:

```
| Domain | Method    | URI                                                | Name                                   | Action                                                                           | Middleware
|        | POST      | api/v1/baskets                                     | baskets.store                          | GetCandy\Api\Http\Controllers\Baskets\BasketController@store                     | api.client,api.currency,api.customer_groups,api.locale,api.tax
```

**Comment by Jamiewarb** [comment]
Hey Alec,

Thanks for the response.

The definition is indeed in [`routes/api.client.php`](https://github.com/getcandy/candy-api/blob/dev/routes/api.client.php#L45), on line 45:


```php
$router->resource('baskets', 'Baskets\BasketController', [
    'except' => ['edit', 'create', 'destroy'],
]);
```

The resource is created, which is creating the PUT/PATCH update method.

Running `php artisan route:list | grep "BasketController@update"` will show you this route, and that it calls the undefined store method:

```
$ php artisan route:list | grep "BasketController@update"
|        | PUT       | api/v1/baskets/saved/{basket}                      |                                        | GetCandy\Api\Http\Controllers\Baskets\SavedBasketController@update               | auth:api,api.currency,api.customer_groups,api.locale,api.tax                 |
|        | PUT|PATCH | api/v1/baskets/{basket}                            | baskets.update                         | GetCandy\Api\Http\Controllers\Baskets\BasketController@update                    | api.client,api.currency,api.customer_groups,api.locale,api.tax
```

**Comment by alecritson** [comment]
Hey @Jamiewarb 

Sorry, I'm confused at the moment.

So in relation to the first route you mentioned `api/v1/baskets/saved/{basket}` this is defined in my comment above, but `api/v1/baskets/{basket}` does not have an update method, it looks like it wasn't added to the `except` array originally.

**Comment by Jamiewarb** [comment]
Eek, I made a mistake when I quoted the route `api/v1/baskets/saved/{basket}`. I actually meant `api/v1/baskets/{basket}`.

**Comment by alecritson** [comment]
It may well get added in the future, I just did a quick commit though to remove it to avoid confusion for the time being!

**Comment by Jamiewarb** [comment]
Okay great, thank you!

The candy client also has a `Basket()->Put()` Job, which I believe goes through to the route we discussed above. This is what lead me to this problem.
