### ISSUE TITLE
Search Error "[dis_max] requires 'queries' field with at least one clause"

### ISSUE THREAD

**Issue by surpaimb** [getcandy/candy-api#88]
I am getting this error when using "api/v1/search" API. My code is fork from "getcandy/candy-api/tree/dev", using ElasticSearch 6.4.2.

**Comment by alecritson** [comment]
Hey @surpaimb 

I've updated the config wish should be published when you do
```
php artisan vendor:publish --tag=config
```

If you take a look here [https://github.com/getcandy/candy-api/blob/dev/config/getcandy.php#L139](https://github.com/getcandy/candy-api/blob/dev/config/getcandy.php#L139) you'll see there is some config I think you're missing.
