### ISSUE TITLE
 https://github.com/getcandy/candy-store have found 404 error

### ISSUE THREAD

**Issue by mcmc4519** [getcandy/candy-api#89]
Hi!
On page  https://github.com/getcandy/candy-store I can't found instructions about candy-hub.
Where I can find guidelines for your products?

**Comment by alecritson** [comment]
Hi

Yes we removed this package as we felt that it was outdated and not really reflective of the current state of the project, we're working on docs at the moment.

For the time being if you need help, feel free to [join us on slack](https://join.slack.com/t/getcandy/shared_invite/enQtMzA3NjkzMjQ5OTIyLTY1ZTFiMmM2MGE5ZGVkYjY5ZDk4ZDY1MDUyNWQ1ZGE5YmVhYjg3NGI1MzE2NGI0MDc2ZDFmN2RkNjAzYjJlMWY)
