### ISSUE TITLE
count(null) throws error on php >=7.2

### ISSUE THREAD

**Issue by dhonions** [getcandy/candy-api#9]
On fresh candy-store install on php 7.2.1:

Visiting:
https://getcandy.local/hub/catalogue-manager/products

(no products set-up in store)

get a loading icon instead of `No Products Found`

 This is because a call to the api at:
`https://getcandy.local/api/v1/products?type=product&per_page=25&current_page=1&includes=channels,customer_groups,family,attribute_groups`

sends back a response of:
`message: "count(): Parameter must be an array or an object that implements Countable"`

because:- 

` if (count($ids)) { }`

[ie. **count(null)**] throws an error on php >=7.2 in the following classes:

```
/src/API/Products/Services/ProductService.php
/src/API/User/Services/UserService.php
```

Use instead:
`if (!empty($ids)) { }`

further:
https://github.com/yiisoft/yii/issues/4167

let me know if you want a pull request for this.

**Comment by InkedCurtis** [comment]
I've also got this problem, any update?

**Comment by christophwolff** [comment]
+1

**Comment by dhonions** [comment]
For a quick fix just change:-

if (count($ids)) {
to
if (!empty($ids)) {

in

/src/API/Products/Services/ProductService.php
/src/API/User/Services/UserService.php

**Comment by InkedCurtis** [comment]
@dhonions Yeah that's all good & well, I just hate dirty fixes & hate modifying the repo's inside vendor

**Comment by dhonions** [comment]
Totally agree - stick it in as a pull-request - I tried, but it disappeared.

**Comment by alecritson** [comment]
Hey Guys,

We've been working on a bunch of updates that are in the final review stages and we just need to merge them in and set a release. We will be fixing any issues we see on this repo too.

**Comment by christophwolff** [comment]
I updated the akismet plugin and it was gone.
