### ISSUE TITLE
Link to ProductCategoryController in api.php is incorect

### ISSUE THREAD

**Issue by zmerrychristmas** [getcandy/candy-api#92]
Link to function ProductCategoryController@destroy
## Expected Behavior
    should change to this $router->delete('products/{product}/categories/{category}', 'Products\ProductCategoryController@destroy');

## Current Behavior
at this line it wrong link to:     should change to this $router->delete('products/{product}/categories/{category}', 'Products\Produ\ctCategoryController@destroy');

## Possible Solution
Just a link file not correct

## Steps to Reproduce
run: php artisan route:list

**Comment by alecritson** [comment]
This should be fixed in [0.1.2](https://github.com/getcandy/candy-api/releases/tag/v0.1.2)
